### ISSUE TITLE
Test for credit paid back (cash and via bank transfer)

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_shopping_cart#57]

**Comment by semteacher** [comment]
Payback possiblr via 2 buttons and via credit mamager.
1. In this case - should I test only 2 buttons?
2. Amoubts could be different depending discount and rouding and cancalation fee. Look like too many tests could be involved
2.1 Alternatively - I can force existing amount of credit via DB for user... But in this case tests will be very simple - after pressing "refund" - "credit" row just disappears ? 
I am asking because it was already in test - except no differentiation between bank/cash refund

**Comment by bernhard-wunderbyte** [comment]
The "simple" test should be enough for now.
